### ISSUE TITLE
Build fails with minifyEnabled

### ISSUE THREAD

**Issue by OscarSpruit** [cashapp/cash-app-pay-android-sdk#122]
After adding the Cash App Pay SDK to our project and building the project with `minifyEnabled true` we are getting the following error:
```
ERROR: R8: Missing class kotlinx.serialization.KSerializer (referenced from: kotlinx.datetime.serializers.InstantIso8601Serializer)
Missing class kotlinx.serialization.Serializable (referenced from: kotlinx.datetime.Instant)
```
Besides this SDK nothing else is using kotlinx datetime in our project. Now I'm not fully sure if this error comes from your SDK or maybe it's already an issue in kotlinx datetime. I couldn't really find anything on this particular error.

I'm assuming it is safe to ignore this error in the ProGuard rules, since kotlinx serialization is not used. Can you verify this? Or do you maybe know any other solutions?

Cash App Pay SDK version: 2.2.0

**Comment by pedronveloso** [comment]
This PR addresses this issue: https://github.com/cashapp/cash-app-pay-android-sdk/pull/125
